[functions]
  node_bundler = "esbuild"

# Scheduled Function "intervals-tagesziel"
[functions."intervals-tagesziel"]
  # Cron-Zeit in UTC:
  # 1 23 * * *  = 23:01 UTC â†’ 00:01 (Europa/Berlin) in der Winterzeit
  schedule = "1 23 * * *"
